header: |
  made by xPand
   __  __ _ ____              _____            _
  |  \/  (_)  __ \           |  __ \          | |
  | \  / |_| |__) |_ _ ______| |__) |__   ___ | |
  | |\/| | |  ___/ _` |______|  ___/ _ \ / _ \| |
  | |  | | | |  | (_| |      | |  | (_) | (_) | |
  |_|  |_|_|_|   \__,_|      |_|   \___/ \___/|_|

paths:
  - dev-ops/common/actions
templates:
  - source: "dev-ops/common/templates/.env.dist"
    destination: ".env"

const:
  APP_NAME: "MiPa-Pool"
  APP_URL: "http://localhost"
  APP_TIMEZONE: "Europe/Berlin"

  LOG_CHANNEL: "stack"

  DB_CONNECTION: "mysql"
  DB_HOST: "127.0.0.1"
  DB_PORT: "3306"
  DB_DATABASE: "MiPaPo"
  DB_USERNAME: "root"
  DB_PASSWORD: ""

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"

  REDIS_HOST: "127.0.0.1"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"

  MAIL_DRIVER: "smtp"
  MAIL_HOST: "smtp.mailtrap.io"
  MAIL_PORT: "2525"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_ENCRYPTION: "null"

  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION: "eu-central-1"
  AWS_BUCKET:

  PUSHER_APP_ID:
  PUSHER_APP_KEY:
  PUSHER_APP_SECRET:
  PUSHER_APP_CLUSTER: "eu"

  JWT_TTL: 1440

environments:
  dev:
    templates:
      - source: "dev-ops/dev/templates/.env.dist"
        destination: ".env"
    paths:
      - "dev-ops/dev/actions"

  github:
    templates:
      - source: "dev-ops/github/templates/.env.dist"
        destination: ".env"
    paths:
      - "dev-ops/github/actions"
