name: setup
author: Eric Heinzl
jobs:
  setup:
    - uses: shivammathur/setup-php@v1
      with:
        php-version: '7.4'
        tools: phpunit
    - name: Give access rights
      run: chmod +x ./psh.phar