name: Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  setup:
    name: "setup"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          tools: phpunit
      - name: Give access rights.
        run: chmod +x ./psh.phar

  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - name: Run init script.
        run: ./psh.phar github:init

  unit:
    name: "php-unit"
    runs-on: ubuntu-latest
    steps:
      - name: Execute PHPUnit tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: app/Components/Common/Database/database.sqlite
        run: ./psh.phar github:unit