name: build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    - name: "Branch: master"
    runs-on: ubuntu-latest
    steps:
      - name: Run init script.
        run: ./psh.phar github:init
      - name: Execute Unit-Tests via PHPUnit.
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: app/Components/Common/Database/database.sqlite
        run: ./psh.phar github:unit
