name: init

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  init:
    - name: "Branch: master"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          php-version:
            - 7.4
            - 7.3
            - 7.2
          tools: phpunit
      - name: Give access rights.
        run: chmod +x ./psh.phar