name: CI

on:
  pull_request:
    branches:
      - master
      - release
      - '2.0'
  push:
    branches:
      - master
      - release
      - '2.0'

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
      - name: Install Application
        run: composer install && composer install-prod

  phpunit:
    name: "testing - phpunit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          tools: phpunit
      - name: Install Application
        run: composer install && composer install-prod
      - name: Run PHPUnit
        run: composer test
